= `"io"` Test Utilities

image:https://travis-ci.org/vulpine-io/io-test.svg?branch=master["Build Status", link="https://travis-ci.org/vulpine-io/io-test"]
image:https://img.shields.io/github/v/tag/vulpine-io/io-test?label=version[Latest Tag, link=https://github.com/vulpine-io/io-test/tags]
image:https://img.shields.io/badge/go-docs-ff69b4["Go Doc", link="https://pkg.go.dev/github.com/vulpine-io/io-test"]
image:https://goreportcard.com/badge/github.com/vulpine-io/io-test["Go Report Card", link="https://goreportcard.com/report/github.com/vulpine-io/io-test"]
image:https://codecov.io/gh/vulpine-io/io-test/branch/master/graph/badge.svg["Code Coverage", link="https://codecov.io/gh/vulpine-io/io-test"]

Configurable mock/test implementations of commonly used `io` package interfaces.

== `io.Reader` | `io.ReadCloser`

Using `iotest.ReadCloser` you can mock an instance of `io.Reader` or
`io.ReadCloser` (or just `io.Closer` if you wanted).

The mock/test struct allows you to configure when/if errors are returned, what
"written byte" counts are returned, and the contents of the source to read from.
Additionally, the struct will contain a count of calls to `Read` and `Close`.

.Basic Usage
[source, go]
----
package main

import (
  "fmt"

  "github.com/vulpine-io/io-test/v1/pkg/iotest"
)

func main() {
  reader := new(iotest.ReadCloser)
  buffer := make([]byte, 10)

  fmt.Println(reader.Read(buffer)) // 10 <nil>
  fmt.Println(string(buffer))      // abcdefghij
  fmt.Println(reader.ReadCalls)    // 1
}
----

== `io.Writer` | `io.WriteCloser`

Using `iotest.WriteCloser` you can mock an instance of `io.Writer` or
`io.WriteCloser` (or just `io.Closer` if you wanted).

The mock/test struct allows you to configure when/if errors are returned and
what "written byte" counts are returned.  Additionally, the struct will contain
a count of calls to `Write` and `Close` in addition to a slice of all the data
passed to the `Write` method.

.Basic Usage
[source, go]
----
package main

import (
  "fmt"

  "github.com/vulpine-io/io-test/v1/pkg/iotest"
)

func main() {
  writer := new(iotest.WriteCloser)
  data := []byte("hey there!")

  fmt.Println(writer.Write(data))          // 10 <nil>
  fmt.Println(string(writer.WrittenBytes)) // hey there!
  fmt.Println(writer.WriteCalls)           // 1
}
----

== Planned

* `io.ByteScanner`
* `io.RuneScanner`
* `io.ByteReader`
* `io.RuneReader`
